name: stats
dependencies:
  - python=3.7.1
  - numpy=1.15.4
  - pandas=0.23.4
  - scipy=1.1.0
  - matplotlib=3.0.2
  - plotly=3.7.0
  - scikit-learn=0.20.1
  - cython
  - pip=18.1
  - pip:
    - okada_wrapper
    - pyproj
